name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
      - 'tests/**'
      - 'feature/**'
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:

  ci-gate:
    name: 🛡️ Gatekeep CI
    if: >-
      ${{
        !(github.event_name == 'pull_request' && github.event.pull_request.user.login == 'WerWolvTranslationBot')
      }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running CI"

  win_msvc:
    needs: ci-gate
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture_name: "x86_64"
            vs_arch: "amd64"
            runner_os: "windows-2025"
          - architecture_name: "arm64"
            vs_arch: "amd64_arm64"
            runner_os: "windows-11-arm"

    runs-on: ${{ matrix.runner_os }}
    name: 🪟 Windows MSVC ${{ matrix.architecture_name }}

    env:
      CCACHE_DIR:      "${{ github.workspace }}/.ccache"

    permissions:
      id-token: write
      attestations: write

    steps:
      - name: 🧰 Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: 🫧 Setup Visual Studio Dev Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.vs_arch }}

      - name: 📜 Setup ccache
        uses:  hendrikmuhs/ccache-action@v1.2.23
        id:    cache-ccache
        with:
          key: ${{ runner.os }}-msvc-${{ matrix.vs_arch }}-ccache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-msvc-${{ matrix.vs_arch }}-ccache
          max-size: 1G

      - name: 📦 Install vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with:
          committish: 66c0373dc7fca549e5803087b9487edfe3aca0a1
          cache-key: ${{ runner.os }}-msvc-${{ matrix.vs_arch }}-vcpkg


      - name: ⬇️ Install dependencies
        run: |
          cp dist/vcpkg.json vcpkg.json

      - name: ⬇️ Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: ⬇️ Install .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.100'

      - name: 📜 Set version variable
        run: |
          "IMHEX_VERSION=$(Get-Content VERSION -Raw)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # Windows cmake build
      - name: 🛠️ Configure CMake
        run: |
          mkdir -p build

          # Echo the VCPKG_ROOT env var
          Write-Host "VCPKG_ROOT: $env:VCPKG_ROOT"
          Write-Host "VCPKG_DEFAULT_BINARY_CACHE: $env:VCPKG_DEFAULT_BINARY_CACHE"
                    
          cmake -G "Ninja" -B build                                                   `
            --preset vs2022                                                           `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" `
            -DCMAKE_C_COMPILER="$($(Get-Command cl.exe).Path)"                        `
            -DCMAKE_CXX_COMPILER="$($(Get-Command cl.exe).Path)"                      `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache                                        `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache                                      `
            -DCMAKE_INSTALL_PREFIX="$(Join-Path $PWD 'install')"                      `
            -DIMHEX_GENERATE_PACKAGE=ON                                               `
            -DCMAKE_BUILD_TYPE="$env:BUILD_TYPE"                                      `
            -DVCPKG_BUILD_TYPE=release                                                `
            -DIMHEX_PATTERNS_PULL_MASTER=ON                                           `
            -DIMHEX_COMMIT_HASH_LONG="$env:GITHUB_SHA"                                `
            -DIMHEX_COMMIT_BRANCH="$($env:GITHUB_REF -replace '.*/', '')"             `
            -DDOTNET_EXECUTABLE="C:/Program Files/dotnet/dotnet.exe"                  `
            -DCPACK_WIX_ROOT="$($env:USERPROFILE -replace '\\','/')/.dotnet/tools"    `
            .

      - name: 🛠️ Build
        run: |
          cd build
          ninja install

      - name: 🕯️ Install WiX Toolkit
        run: |
          & "C:/Program Files/dotnet/dotnet.exe" tool install --global wix@6.0.2
          & "$($env:USERPROFILE -replace '\\','/')/.dotnet/tools/wix" extension add --global WixToolset.UI.wixext/6.0.2

      - name: 📦 Bundle MSI
        run: |
          cd build
          cpack
          mv ImHex-*.msi ../imhex-${{ env.IMHEX_VERSION }}-Windows-MSVC-${{ matrix.architecture_name }}.msi

      - name: 🗝️ Generate build provenance attestations
        uses: actions/attest-build-provenance@v4
        if: ${{ github.event.repository.fork == false && github.event_name != 'pull_request' }}
        with:
          subject-path: |
            imhex-*.msi

      - name: ⬆️ Upload Windows Installer
        uses: actions/upload-artifact@v7
        if: false # The MSVC builds should not really be used, they're still packaged for testing’s sake though
        with:
          if-no-files-found: error
          name: Windows Installer MSVC ${{ matrix.architecture_name }}
          path: |
            imhex-*.msi
