name: "Unit Tests"

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
      - 'tests/**'
      - 'coverage'
  pull_request:
    branches:
      - 'master'
      - 'releases/**'
  workflow_dispatch:

jobs:
  tests:
    name: 🧪 Unit Tests
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: mxschmitt/action-tmate@master
        name: Setup tmate session
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}